package cn.hfnu.ssmtest.mapper;

import cn.hfnu.ssmtest.po.TbBook;
import cn.hfnu.ssmtest.po.TbBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int countByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int deleteByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int insert(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int insertSelective(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    List<TbBook> selectByExample(TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    TbBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbBook record, @Param("example") TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int updateByExample(@Param("record") TbBook record, @Param("example") TbBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int updateByPrimaryKeySelective(TbBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_book
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    int updateByPrimaryKey(TbBook record);
}