package cn.hfnu.ssmtest.po;

public class TbBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.id
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.name
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.author
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book.price
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.id
     *
     * @return the value of tb_book.id
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.id
     *
     * @param id the value for tb_book.id
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.name
     *
     * @return the value of tb_book.name
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.name
     *
     * @param name the value for tb_book.name
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.author
     *
     * @return the value of tb_book.author
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.author
     *
     * @param author the value for tb_book.author
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book.price
     *
     * @return the value of tb_book.price
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book.price
     *
     * @param price the value for tb_book.price
     *
     * @mbggenerated Mon Jun 04 20:20:21 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}